# Generated by Django 5.2.8 on 2025-11-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="Укажите страну",
                max_length=50,
                null=True,
                verbose_name="Страна",
            ),
        ),
    ]
